name: gravity_toolkit
channels:
  - conda-forge
dependencies:
  - boto3
  - cartopy
  - future
  - h5py
  - ipywidgets
  - ipympl
  - jupyterlab
  - jupyterlab_widgets
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - tk
  - pip
  - pip:
     - git+https://github.com/tsutterley/geoid-toolkit.git
