name: gravity-docs
channels:
  - conda-forge
dependencies:
  - boto3
  - docutils<0.18
  - fontconfig
  - freetype
  - future
  - graphviz
  - lxml
  - markupsafe==2.0.1
  - matplotlib
  - notebook
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - texlive-core
  - tk
  - pip:
     - sphinx-argparse>=0.4
     - ..
